-- MySQL Script generated by MySQL Workbench
-- Thu Feb 22 14:49:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`super_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`super_admin` (
  `idsuper_admin` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `mot de passe` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idsuper_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot de passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evenement` (
  `idevenement` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `partenaire` VARCHAR(100) NOT NULL,
  `created_at` VARCHAR(100) NOT NULL,
  `update_at` VARCHAR(100) NOT NULL,
  `admin_idadmin` INT NOT NULL,
  `super_admin_idsuper_admin` INT NOT NULL,
  PRIMARY KEY (`idevenement`),
  INDEX `fk_evenement_admin1_idx` (`admin_idadmin` ASC) ,
  INDEX `fk_evenement_super_admin1_idx` (`super_admin_idsuper_admin` ASC) ,
  CONSTRAINT `fk_evenement_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `mydb`.`admin` (`idadmin`)
    ,
  CONSTRAINT `fk_evenement_super_admin1`
    FOREIGN KEY (`super_admin_idsuper_admin`)
    REFERENCES `mydb`.`super_admin` (`idsuper_admin`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`catégorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`catégorie` (
  `idcatégorie` INT NOT NULL AUTO_INCREMENT,
  `nom_evenement` VARCHAR(100) NOT NULL,
  `created_at` VARCHAR(100) NOT NULL,
  `update_at` VARCHAR(100) NOT NULL,
  `evenement_idevenement` INT NOT NULL,
  PRIMARY KEY (`idcatégorie`),
  INDEX `fk_catégorie_evenement_idx` (`evenement_idevenement` ASC) ,
  CONSTRAINT `fk_catégorie_evenement`
    FOREIGN KEY (`evenement_idevenement`)
    REFERENCES `mydb`.`evenement` (`idevenement`)
    )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
